name: Deploy
run-name: Deploy from ${{ github.event_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI ]
    types:
      - completed

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u vtsv -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build images
        run: docker compose build

      - name: Push images
        run: docker compose push

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    environment: Production
    env:
      TZ: America/New_York

    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Set SSH key permissions
        run: chmod 600 ~/.ssh/id_rsa

      - name: Add SSH host keys
        run: ssh-keyscan challenge.fingerlakesrunners.org > ~/.ssh/known_hosts

      - name: Pull images
        run: ssh root@challenge.fingerlakesrunners.org "cd /var/leaderboards && docker-compose pull"

      - name: Run images
        run: ssh root@challenge.fingerlakesrunners.org "cd /var/leaderboards && docker-compose up -d"